### ISSUE TITLE
May to-do list

### ISSUE THREAD

**Issue by BrodiePearson** [cassidymwagner/fluidsf#11]
I'm going to use this issue to keep track of some adjustments/capabilities that we should add in the near future:

- [x] Change meridional/zonal (m/z) notation and text to y-oriented/x-oriented (y/x) for general applications. M/Z only really makes sense for lat-lon-equivalent datasets
- [x] Add 2D maps of SFs for regularly-gridded data
- [x] Add 1D (track) structure function calculations
- [x] Add 3D (LES) structure function calculations
- [x]  Add options for SF_TT and SF_SS across all modules

**Comment by cassidymwagner** [comment]
1D structure functions in progress on #12

**Comment by cassidymwagner** [comment]
Meridional/zonal to y/x ready on #13

**Comment by cassidymwagner** [comment]
User-set binning in progress on #14

**Comment by cassidymwagner** [comment]
3D structure functions in progress on #15

**Comment by BrodiePearson** [comment]
@cassidymwagner I added a new bullet to add SF_TT and SF_SS calculators across all modules once all the modules are merged into main
